
# cross compiler
CXX = i686-elf-g++
CXXFLAGS = --std=c++11 -ffreestanding -fno-builtin -nostdlib -nostdinc -O2 -Wall -Wextra -fno-exceptions -fno-rtti
LNKFLAGS = -T linker.ld -ffreestanding -O2 -nostdlib -lgcc

SRC = boot.cc entry.cc kernel.cc driver/vga.cc standard.cc io.cc
OBJ = $(SRC:.cc=.o)
BIN = kernel

CRTBEGIN:=$(shell $(CXX) $(CXXFLAGS) -print-file-name=crtbegin.o)
CRTEND:=$(shell $(CXX) $(CXXFLAGS) -print-file-name=crtend.o)

%.o: %.cc
	# recompile every file every time
	$(CXX) $(CXXFLAGS) -c $< -o $@

# NOTE: these must be linked in this order
# crti.o defines the beginning of the .init and .fini
# functions, and ctrn.o defines the ends of each,
# the autogenerated crtbegin.o and crtend.o contain
# the body of these functions.
$(BIN): $(OBJ) crti.o $(CRTBEGIN) $(CRTEND) crtn.o
	$(CXX) $(LNKFLAGS) $^ -o $(BIN)

clean:
	$(RM) $(OBJ) $(BIN)
